apiVersion: cae.cisco.com/v1
kind: SSOAuthConfig
metadata:
  # FQDN de ta Route (doit exister et être acceptée)
  name: santequebec.cloudapps.cisco.com
  namespace: santequebec
spec:
  provider:
    idp: okta          # requis par le schéma, même si tu n'utilises pas "platform" SSO
    sso: application   # ton app gère l'auth
    cors: application  # ton app gère CORS (mets "platform" si tu veux que la plateforme injecte les headers CORS)
  contexts:
    - context: /
      contextMatch: prefix
      policyType: public
